-- 001_schema.sql
-- Home IoT Monitor: Database schema for sensor readings, weather observations,
-- sensor configuration, and ingestion logging.
--
-- Tables:
--   1. sensor_config       - MAC-to-room mapping with assignment history
--   2. sensor_readings     - RuuviTag sensor data (monthly partitioned)
--   3. weather_observations - FMI weather data (monthly partitioned)
--   4. ingestion_log       - Ingestion metrics and error tracking


-- ============================================================================
-- 1. SENSOR CONFIG
-- ============================================================================
-- Maps MAC addresses to rooms with timestamp-based assignment history.
-- Supports repurposing (tag moves rooms) and replacement (new tag in same room).
-- unassigned_at = NULL means the assignment is currently active.

CREATE TABLE sensor_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mac_address text NOT NULL,
  display_name text NOT NULL,
  room_name text,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  unassigned_at timestamptz,
  notes text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_sensor_config_mac ON sensor_config (mac_address);
CREATE INDEX idx_sensor_config_active ON sensor_config (mac_address)
  WHERE unassigned_at IS NULL;


-- ============================================================================
-- 2. SENSOR READINGS (monthly partitioned by measured_at)
-- ============================================================================
-- Stores decoded RuuviTag sensor values plus the raw JSON payload.
-- Pressure is stored in Pascals as received from the Ruuvi Station app.

CREATE TABLE sensor_readings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  mac_address text NOT NULL,
  measured_at timestamptz NOT NULL,
  temperature double precision,
  humidity double precision,
  pressure double precision,
  battery_voltage double precision,
  rssi integer,
  movement_counter integer,
  tx_power integer,
  accel_x double precision,
  accel_y double precision,
  accel_z double precision,
  measurement_sequence integer,
  data_format integer,
  sensor_name text,
  is_outlier boolean DEFAULT false,
  outlier_reason text,
  raw_payload jsonb,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (measured_at, id)
) PARTITION BY RANGE (measured_at);

-- Unique index for deduplication: same MAC + same timestamp = duplicate
CREATE UNIQUE INDEX idx_sensor_readings_dedup
  ON sensor_readings (mac_address, measured_at);


-- ============================================================================
-- 3. WEATHER OBSERVATIONS (monthly partitioned by observed_at)
-- ============================================================================
-- Stores FMI weather observations from Helsinki-Vantaa airport (FMISID 100968).
-- 13 parameters mapped from the FMI WFS multipointcoverage response.

CREATE TABLE weather_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  observed_at timestamptz NOT NULL,
  fmisid integer NOT NULL DEFAULT 100968,
  temperature double precision,
  wind_speed double precision,
  wind_gust double precision,
  wind_direction double precision,
  humidity double precision,
  dew_point double precision,
  precipitation_1h double precision,
  precipitation_intensity double precision,
  snow_depth double precision,
  pressure double precision,
  visibility double precision,
  cloud_cover double precision,
  weather_code double precision,
  raw_values text,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (observed_at, id)
) PARTITION BY RANGE (observed_at);

-- Unique index for deduplication: same station + same timestamp = duplicate
CREATE UNIQUE INDEX idx_weather_obs_dedup
  ON weather_observations (fmisid, observed_at);


-- ============================================================================
-- 4. INGESTION LOG
-- ============================================================================
-- Tracks ingestion metrics and errors for both Ruuvi and FMI sources.
-- NOT partitioned -- this is a small table.

CREATE TABLE ingestion_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  status text NOT NULL,
  readings_count integer DEFAULT 0,
  duplicates_count integer DEFAULT 0,
  outliers_count integer DEFAULT 0,
  error_message text,
  details jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_ingestion_log_source_time
  ON ingestion_log (source, created_at DESC);


-- ============================================================================
-- 5. DEFAULT PARTITIONS (safety nets)
-- ============================================================================
-- Catch any rows that don't match a specific monthly partition.

CREATE TABLE sensor_readings_default
  PARTITION OF sensor_readings DEFAULT;

CREATE TABLE weather_observations_default
  PARTITION OF weather_observations DEFAULT;


-- ============================================================================
-- 6. INITIAL MONTHLY PARTITIONS
-- ============================================================================
-- Create partitions for current month (2026-02) and next month (2026-03).

-- sensor_readings partitions
CREATE TABLE sensor_readings_2026_02
  PARTITION OF sensor_readings
  FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

CREATE TABLE sensor_readings_2026_03
  PARTITION OF sensor_readings
  FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');

-- weather_observations partitions
CREATE TABLE weather_observations_2026_02
  PARTITION OF weather_observations
  FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

CREATE TABLE weather_observations_2026_03
  PARTITION OF weather_observations
  FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
